import fs from 'node:fs';

const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const titleOf = html => (html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1] || '').replace(/<[^>]+>/g, '').trim();
const labelsOf = html => [...html.matchAll(/<label[^>]*>([^<]+)/gi)].map(m => m[1].trim()).filter(Boolean);
const tag = (name, text) => `<section class="content-section"><h2>${name}</h2>${text}</section>`;

/* Each entry is deliberately tied to the tool's calculation target.  This is
   source copy, not a generic disclaimer template. */
const calculators = {
  'banner-area.html': ['wide-format material planning', 'Record the finished banner width and height from the approved artwork, then keep feet and inches in the same measurement system. The reference value is not part of the area calculation; use it only when the job ticket asks for a comparison.', 'For a 12 ft by 3 ft banner, the printable face is 36 sq ft. Use that figure to price media and print area, then add hems, pole pockets, seams and a separate production allowance.', 'confusing face area with the wider media needed for hems or edge finishing', 'Roll width, overlap, seam placement, ink coverage and usable printable width are supplier and machine conditions.'],
  'bleed-safe-area.html': ['artwork preflight', 'Take trim from the approved dieline or finished-size job ticket. Set the safe inset from the client’s live-content rule, not from the bleed value; bleed extends outward while safe area moves inward.', 'A 210 mm trim panel with a 3 mm bleed and 4 mm safe inset becomes a 216 mm file edge-to-edge, with important copy held inside the 202 mm safe span.', 'treating safe area as extra bleed or measuring it from the file edge', 'A supplied dieline, folding tolerance and finishing process can require a different inset.'],
  'bleed-size.html': ['artwork setup and prepress', 'Enter the trim dimension from the approved finished-size specification and the bleed required on every cut edge. The bleed value is per side, so the calculator adds it twice across a dimension.', 'A 90 mm business-card width with 3 mm bleed on both edges needs a 96 mm artwork width. That is the file size before any safe-area rule is applied.', 'adding bleed only once or using the flat, folded size where trim was requested', 'Die cutting, folding and large-format finishing can require job-specific bleed beyond this geometry check.'],
  'book-cover-size-calculator.html': ['cover artwork planning', 'Use trim width and height from the book specification, the measured or calculated spine, and the printer’s stated bleed. These are cover-panel dimensions, not the interior page size.', 'For a 152 mm by 229 mm book, a 14 mm spine and 3 mm bleed, the spread is 324 mm wide and 235 mm high. Build the cover file to that spread before placing barcode or spine type.', 'omitting one cover panel, using page count as a spine width, or placing live type in bleed', 'Hinge allowances, case-wrap turn-ins, laminate and a printer-supplied template can change the final cover geometry.'],
  'book-spine-width-calculator.html': ['book estimating and cover planning', 'Get page count from the final interior PDF, leaf caliper from the selected stock data sheet or a compressed sample, and any allowance from the binding specification. Pages become leaves by dividing by two.', 'A 160-page text block on 0.095 mm stock has 80 leaves; it contributes 7.60 mm before a 0.50 mm allowance, for an 8.10 mm planning spine.', 'multiplying every page by caliper, using uncompressed paper thickness, or assuming all binding methods need the same allowance', 'Paper bulk changes under pressure; glue, lining, boards and binder tolerances must be confirmed with the production supplier.'],
  'book-weight.html': ['shipping and fulfillment estimation', 'Use final page count, the actual page or sheet area, and GSM from the stock specification. Include cover, endpapers, inserts and packaging as separate components rather than hiding them in the text-paper estimate.', 'A 128-page A5 book has 64 leaves. With 0.062 m² leaves at 100 gsm, the text block is about 397 g before cover and binding weight are added.', 'counting pages as sheets or using finished trim area when the printed sheet has a different area', 'Moisture, coating, board cover, adhesive and packaging can materially change shipment weight.'],
  'booklet-creep-calculator.html': ['saddle-stitch imposition', 'Use the final page count in multiples of four and the measured folded-sheet caliper. The required positive reference field is a validation input; use the job ticket’s chosen production setting rather than inventing a press allowance.', 'A 64-page booklet has 16 nested sheets. At 0.085 mm per folded sheet, the outer-to-inner creep estimate is 1.28 mm, guiding the shingling or trim compensation discussion.', 'using cover thickness as text-sheet caliper or calculating creep for perfect-bound books', 'Fold sequence, stock compression, cover construction and trimmer tolerance determine the production adjustment.'],
  'booklet-page-order-calculator.html': ['saddle-stitch imposition planning', 'Enter the total finished page count, including blank pages, and make it divisible by four. The auxiliary fields are not page-order inputs; use the imposition sheet and printer workflow for the complete signature map.', 'For a 16-page booklet, the outside of the first sheet pairs pages 16 and 1, while its reverse pairs 2 and 15. Use the result as a quick pagination check before making a full imposition.', 'dropping blank pages, reading reader spreads as printer spreads, or applying saddle-stitch order to perfect binding', 'This short pairing check does not replace signature planning, creep compensation or RIP imposition.'],
  'coil-binding.html': ['finishing specification and purchasing', 'Use final page count, compressed sheet caliper, and a documented allowance for covers and turning clearance. The calculated stack is a starting point for choosing a coil range, not a manufacturer size recommendation.', 'A 200-page book has 100 leaves. At 0.10 mm each plus 1.5 mm cover and clearance allowance, the planning stack is 11.5 mm before selecting the next suitable coil range.', 'using page count as leaf count or selecting a coil with no page-turn clearance', 'Punch pattern, cover board, laminate and coil supplier range tables must be checked before ordering.'],
  'cost-per-piece.html': ['quoting finished units', 'Enter material, labour and finishing costs from the estimate and use the saleable finished quantity, not press sheets or gross impressions. Separate setup costs if they are recovered elsewhere in the quote.', 'If material is 180, labour is 90 and finishing is 30 for 1,000 saleable cards, the direct cost is 0.30 per card. Compare it with the selling price before applying margin.', 'dividing by gross run quantity after spoilage or omitting a finishing charge because it occurs later', 'This is a direct-cost view; overhead, tax, freight, rejects and commission may need their own estimate lines.'],
  'dpi-print-size-calculator.html': ['prepress image sizing', 'Use the delivered pixel width and height and the target output PPI specified by the job. DPI describes marking capability of an output device; this calculator converts image pixels at a chosen PPI.', 'A 3000 by 2400 pixel image at 300 PPI prints at 10 by 8 inches without interpolation. At 150 PPI it may be usable at a larger size only when viewing distance and subject allow it.', 'calling image PPI printer DPI or resizing an image in layout software without checking effective resolution', 'RIP screening, interpolation and viewing distance influence perceived quality; the result is not a guarantee of press reproduction.'],
  'gripper-margin.html': ['sheet planning and press setup', 'Enter the press-sheet dimension, outer margin and gripper allowance from the press specification or production ticket. The gripper is a press-side non-print area; an outer margin may apply on more than one edge.', 'On a 520 mm sheet with 8 mm outer margin and a 12 mm gripper, the usable direction is reduced by the specified reserved areas before any item count is attempted.', 'counting gripper on every edge or treating it as bleed around the artwork', 'Side guide, tail margin and press-specific printable area vary by equipment and stock.'],
  'gsm-basis-weight-converter.html': ['paper stock comparison and purchasing', 'Enter the supplier’s basis weight in pounds and the stated basis-sheet width and height in inches. Basis weight is not comparable without its grade and basis size; GSM expresses mass per square metre.', 'A 70 lb stock on a 25 by 38 inch basis sheet converts to about 104 gsm. Record both the grade and basis size on the estimate so a similarly named stock is not substituted.', 'converting pounds without basis dimensions or assuming bond, text and cover grades share one basis size', 'Mill specifications and paper category govern the correct basis sheet; verify the supplier data sheet before purchase.'],
  'image-scaling.html': ['artwork revision and preflight', 'Use the original placed dimension and the proposed new dimension from the layout. The reference field does not alter scaling; note the resulting effective PPI separately when raster artwork is enlarged.', 'Scaling a 100 mm image to 125 mm is 125%. If it started at 300 effective PPI, its effective resolution falls to 240 PPI after enlargement.', 'scaling only one dimension unintentionally or assuming percentage scaling preserves raster resolution', 'Vector artwork scales differently from pixels; linked-image resolution and output screening remain separate checks.'],
  'items-per-sheet-calculator.html': ['simple sheet-yield planning', 'Use sheet width and height after deciding whether the supplied values are physical sheet or printable area. Enter finished item dimensions and bleed per edge; do not include gutter unless the job needs it separately.', 'A 500 by 700 mm printable sheet with 90 by 50 mm cards and 3 mm bleed fits 5 across by 6 down, or 30 cards, before gripper and trim-strip decisions.', 'using final item size without bleed or assuming the physical parent sheet is fully printable', 'The tool does not optimize rotation, gutters, gripper, color bars or cutting sequence.'],
  'm-weight.html': ['paper purchasing and freight estimation', 'Use the actual press or parent sheet dimensions in millimetres and the stock GSM. M-weight means the mass of one thousand sheets at that exact size, not a named paper grade.', 'One thousand 700 by 500 mm sheets at 120 gsm weigh 42 kg. Use that result to compare quotes for different parent-sheet choices or estimate handling loads.', 'confusing M-weight with a ream weight or entering trim dimensions when ordering parent sheets', 'Mill tolerance, moisture and carton count affect delivered weight.'],
  'n-up-printing.html': ['layout feasibility planning', 'Record sheet width, height and finished item dimensions from the job ticket. Before relying on the count, decide whether the dimensions already exclude gripper, side guide, gutters and bleed.', 'A 450 by 320 mm printable area with 90 by 50 mm items yields 5 by 6, or 30-up, in the entered orientation. Compare a rotated layout in the imposition calculator if rotation is allowed.', 'assuming an N-up count is a certified press layout or forgetting cut lanes between items', 'Press-side non-print areas, grain direction and finishing equipment may rule out a geometrically possible layout.'],
  'paper-thickness.html': ['stock identification and binding planning', 'Measure a compressed stack with a suitable gauge, count the sheets in that stack, and enter caliper in micrometres if the job uses that unit. Do not derive caliper from GSM alone.', 'A 10.0 mm stack of 100 sheets has a 0.10 mm, or 100 micrometre, planning caliper per sheet. Use that measurement for spine or coil estimates.', 'measuring an uncompressed fluffy stack or treating micrometres and millimetres as the same unit', 'Humidity, coating, compression force and sample size change caliper readings.'],
  'paper-weight-calculator.html': ['paper ordering, mailing and handling estimation', 'Use the actual sheet width and height in millimetres and the specified GSM. For a finished product, first decide whether you need the trimmed piece weight or the parent-sheet weight consumed in production.', 'A 700 by 500 mm sheet at 120 gsm has 0.35 m² area and weighs 42 g. Multiply it by the press-sheet quantity to estimate pallet mass before adding packaging.', 'entering inches as millimetres, using basis weight in place of GSM, or multiplying by impressions when one sheet carries multiple items', 'Mill tolerance, moisture, coating and inserts are outside the sheet-mass formula.'],
  'pixels-required.html': ['image specification before artwork delivery', 'Start with final print width in inches and target PPI from the job’s viewing conditions. The reference field is not used by the pixel calculation; keep height and crop requirements on the artwork brief.', 'A 12 inch image width at 300 PPI requires 3,600 pixels across. Set that requirement before retouching so the supplied image is not enlarged later in layout.', 'using printer DPI instead of image PPI or requesting pixels for trim width while the image must bleed', 'Subject detail, screen ruling, interpolation and viewing distance affect the appropriate target PPI.'],
  'press-sheets-required.html': ['quantity planning and paper purchasing', 'Use the saleable finished quantity, verified items per press sheet, and a spoilage percentage agreed for this job. Items per sheet must come from a usable press layout, not a rough trim-area division.', 'For 10,000 leaflets at 8-up with 5% spoilage, the net requirement is 1,250 press sheets and the planned quantity is 1,313 after rounding up.', 'adding spoilage twice, dividing by pages instead of items per sheet, or rounding down a partial press sheet', 'Makeready, color changes, duplex method and finishing loss may need separate allowances.'],
  'print-imposition-calculator.html': ['prepress and press-sheet planning', 'Use the parent-sheet dimensions, finished trim size, bleed on each edge, gripper and outer margin from the press specification. The calculator compares entered and rotated item orientation within the usable area.', 'A 700 by 500 mm sheet, 90 by 50 mm finished cards, 3 mm bleed, 10 mm outer margins and 12 mm gripper can be compared in both orientations to choose the higher feasible count.', 'using parent sheet as printable area, missing the gripper, or assuming the higher N-up always gives a practical cutting plan', 'Color bars, side guide, gutters, grain direction, work-and-turn and finishing layout are not fully modeled.'],
  'print-job-cost-calculator.html': ['estimating a commercial print job', 'Enter material, setup, labour plus finishing, other variable costs and saleable finished quantity from the quote worksheet. Setup is a fixed job cost; quantity is the number expected to survive spoilage.', 'A job with 420 material, 180 setup, 260 labour and finishing, and 140 other costs for 2,000 saleable pieces costs 0.50 each before overhead and profit.', 'mixing currency units, counting setup per piece before the total, or using press sheets instead of saleable pieces as the divisor', 'Tax, freight, overhead, credit terms and actual spoilage require separate commercial decisions.'],
  'print-run-time.html': ['press scheduling', 'Use planned impressions, sustainable press speed and the number of passes or colors that truly multiply run time. Record make-ready separately; it is not the same as net running time.', 'At 12,000 impressions, 6,000 impressions per hour and four sequential passes, net running time is 8 press hours. Schedule wash-up, drying and finishing around that result.', 'using maximum brochure speed, ignoring passes, or treating makeready as productive runtime', 'Coverage, stock, drying, operator workflow and machine stops can change the production schedule.'],
  'profit-margin.html': ['quote review and pricing', 'Enter selling price and total cost in the same currency. The reference field is not part of the calculation; confirm whether your business reports gross margin, markup or contribution before communicating the result.', 'A 1.20 selling price with 0.75 total cost leaves 0.45 contribution and a 37.5% margin. Use it to check whether the quote can absorb expected spoilage or discounting.', 'confusing margin with markup or excluding setup, freight or finishing from total cost', 'This calculator does not model tax, payment fees, returns or capacity cost.'],
  'ream-weight.html': ['stock ordering and warehouse planning', 'Use the parent-sheet dimensions and GSM; a ream is normally 500 sheets unless the supplier explicitly uses another count. Confirm that the entered size is the purchased sheet, not the finished item.', 'A 700 by 500 mm, 120 gsm sheet weighs 42 g; a 500-sheet ream therefore weighs about 21 kg before wrapping and pallet materials.', 'treating any pack as a 500-sheet ream or mixing trim and parent-sheet sizes', 'Supplier pack counts, moisture and paper tolerance affect shipping and inventory mass.'],
  'remaining-roll.html': ['wide-format inventory control', 'Measure total material length and used length along the roll, and record roll width separately so the remnant can be matched to the next job. Do not estimate used length from printed area without accounting for leaders and gaps.', 'A 50 m roll with 18 m consumed leaves 32 m of linear material. With the recorded width, that becomes a usable remnant only after checking its edge condition.', 'subtracting square metres from linear metres or ignoring unusable leader, trailer and damaged edge', 'Roll tension, telescoping, take-up waste and machine leader requirements affect usable length.'],
  'roll-diameter.html': ['roll handling and media planning', 'Use linear material length, measured material thickness and core diameter from the media specification. Thickness must be expressed consistently with the other dimensions before using the result for clearance planning.', 'A 100 m film at 0.10 mm on a 76 mm core creates a larger wound roll than the bare core; use the estimate to check carriage, storage and printer clearance.', 'using liner-plus-face thickness when only one layer was measured or confusing radius with diameter', 'Compression, winding tension and supplier tolerances mean the result is an estimate rather than a guaranteed roll OD.'],
  'roll-length.html': ['roll-media consumption planning', 'Use material area and roll width in compatible units. Material thickness is a separate physical property; record it for roll-diameter or handling work, not as a substitute for usable width.', 'A 30 m² job on 1.5 m wide usable media needs 20 linear metres before adding leader, trailer, test prints and trimming allowance.', 'dividing by nominal roll width when the printer’s usable width is smaller or mixing square feet and square metres', 'Nesting, panel seams, gaps and roll-end waste can increase required length.'],
  'roll-media-yield.html': ['repeat-job and roll allocation planning', 'Enter available usable roll length and the linear length consumed by one finished job or repeat. The reference field is not part of the yield; write the roll width and nesting rule on the job ticket.', 'If 45 usable metres remain and each banner consumes 2.7 m, the roll can supply 16 whole jobs with 1.8 m left. Decide whether the remainder suits a smaller job.', 'rounding up the number of jobs, treating nominal roll length as usable length, or omitting leader and trailer', 'Take-up, print gaps, seams and rejected panels reduce real yield.'],
  'saddle-stitch-pages.html': ['booklet specification and preflight', 'Enter the total finished page count including cover and intentionally blank pages. The auxiliary fields do not alter the multiple-of-four rule; use signatures and creep tools for the detailed production plan.', 'A 36-page booklet is valid because it forms nine 4-page sheets. A 34-page draft needs two blank pages or a different binding method before imposition.', 'counting cover separately from total pages or assuming any even page count can saddle stitch', 'Press format, cover stock, fold sequence and insert strategy can change signature grouping.'],
  'sheet-yield-waste-calculator.html': ['stock allocation and production planning', 'Enter total available sheets and the number consumed by one complete job or production batch. Keep spoilage as a separate planning calculation so it is not silently included twice.', 'With 2,500 sheets available and 320 sheets per job, seven complete runs are possible and 260 sheets remain. Use the remainder to assess whether a partial repeat is practical.', 'calling the remainder waste before checking whether it can be used on another job', 'Makeready, damage, grain direction and supplier pack counts influence actual usable yield.'],
  'sheets-from-weight.html': ['paper inventory estimation', 'Use total stock weight in kilograms, the true sheet area in square metres and GSM. Area must reflect the sheet you are counting, such as the parent sheet in storage, not the finished trimmed piece.', 'A 210 kg pallet of 700 by 500 mm, 120 gsm stock contains roughly 5,000 sheets because each sheet weighs 42 g. Round down when reserving stock for a job.', 'using grams where kilograms are requested or assuming a weighed pallet excludes wrapping and skids', 'Pallet packaging, moisture and mill tolerance make a weight-derived count approximate.'],
  'signature-count.html': ['book manufacturing planning', 'Use the final page count, including blanks, and the planned pages per signature from the folding scheme. Pages per signature depend on press format and fold pattern, not a universal book rule.', 'A 192-page book planned in 16-page signatures needs 12 signatures. Use that count to plan folding, gathering and sewing or perfect-binding workflow.', 'dividing by leaves instead of pages or choosing a signature size that does not fit the planned press form', 'Insert sections, color forms, fold tolerance and binding method can create mixed signature plans.'],
  'spoilage-allowance.html': ['estimating and purchasing', 'Enter the required saleable quantity and the agreed spoilage rate. Use a rate based on the operation being planned—makeready, press run or finishing—not a generic percentage copied from another job.', 'For 5,000 required pieces at 4% spoilage, plan 5,200 gross pieces before rounding to a workable press-sheet quantity.', 'adding a percentage to net sheets after a separate overage has already been included', 'Actual spoilage depends on stock, coverage, setup, finishing complexity and customer inspection rules.'],
  'wide-format-resolution-calculator.html': ['large-format preflight', 'Use actual image pixels, final printed width and expected viewing distance. The image width and final width determine effective PPI; viewing distance helps decide whether that PPI is appropriate for the intended audience.', 'A 7,200-pixel image printed 120 inches wide delivers 60 PPI. For a distant billboard-style view it may be adequate, while close retail graphics may need more source resolution.', 'using screen DPI in place of image PPI or judging a distant-view graphic by close-up inspection only', 'Substrate, RIP interpolation, ink set, typography and viewing condition affect perceived sharpness.']
};

function calcContent(file, html) {
  const [stage, inputs, example, mistake, limits] = calculators[file];
  const title = titleOf(html), labels = labelsOf(html).map(esc).join(', ');
  return `<section class="content-detail"><div class="content-detail-inner">
${tag('What this calculator solves', `<p>${esc(title)} is used during ${stage}. It turns a stated job condition into a transparent planning number so an estimator, prepress operator or production coordinator can identify the next decision before committing stock, artwork or press time.</p><p>${esc(title)} is a planning tool rather than a production certificate: use its result to document a decision, then retain the source specification with the job.</p>`)}
${tag('How to choose the inputs', `<p>${esc(inputs)}</p><p>The fields on this ${esc(title)} page are: ${labels}. Read the label’s unit literally and convert source measurements before entry. A numeric result is meaningful only when every input refers to the same finished piece, press sheet, roll length or production quantity.</p>`)}
${tag('How the calculation works', `<p>${esc(title)} uses the entered values in the displayed order, preserves the calculation precision internally and rounds the displayed planning value. Where a result represents a count of sheets, jobs or layouts, round up only after deciding which quantity must be whole.</p><p>Check the ${esc(title)} relationship against the job ticket: the arithmetic can be exact while the selected production basis is wrong.</p>`)}
${tag('Worked production example', `<p>${esc(example)}</p><p>Record the ${esc(title)} inputs and result on the estimate or production ticket. That lets a later operator trace whether a change came from quantity, stock, layout or a changed process allowance.</p>`)}
${tag('How to interpret the result', `<p>${esc(title)} provides a planning value, not an automatic release instruction. Apply its result to the relevant quote, material order, artwork brief, press plan, finishing schedule or inventory reservation, then compare it with the approved job specification.</p><p>If the ${esc(title)} value sits close to a sheet, roll or capacity limit, rerun the calculation with the actual machine and supplier conditions before committing.</p>`)}
${tag('Common production mistakes', `<p>A frequent ${esc(title)} error is ${esc(mistake)}. Also confirm that quantity means saleable pieces, sheets, impressions or linear length as labelled; those measures are not interchangeable.</p><p>For ${esc(title)}, keep spoilage, makeready, overage and finishing loss visible as separate assumptions so they are not counted twice.</p>`)}
${tag('Production assumptions and limitations', `<p>${esc(limits)} ${esc(title)} does not certify equipment fit, final colour, binding performance or delivered quality.</p><p>Before releasing a ${esc(title)} decision, confirm the press, stock, RIP, drying, coating, binding and finishing conditions that apply to this job rather than relying on a universal default.</p>`)}
${tag('Related production workflow', `<p>Start with the job ticket and approved artwork or stock specification, use this calculation at the ${esc(stage)} stage, then carry the recorded result into the next estimating, prepress or production decision.</p><div class="related-content"><section><h3>Related calculators</h3><ul><li><a href="/tools/print-imposition-calculator.html">Print Imposition Calculator</a></li><li><a href="/tools/press-sheets-required.html">Press Sheets Required Calculator</a></li></ul></section><section><h3>Related guides</h3><ul><li><a href="/guides/print-imposition.html">Print imposition workflow</a></li></ul></section><section><h3>Related reference</h3><ul><li><a href="/reference/units.html">Print production units</a></li></ul></section></div></section>`)}</div></section>`;
}

const articles = {
  guides: {
    'bleed-trim-safe-area.html': ['Bleed, trim and safe area', 'Preflight begins by separating three boundaries: trim is the finished cut line, bleed is artwork extending beyond it, and safe area protects live content inside it.', 'For a 210 by 297 mm flyer with 3 mm bleed, supply 216 by 303 mm artwork; keep a logo or phone number inside the printer-approved safe inset.', 'Bleed Size Calculator', 'Common Commercial Print Bleed Sizes'],
    'book-spine-width.html': ['Book spine estimation', 'The spine is based on leaves and compressed caliper, not simply total page count. Get a sample or supplier data for the exact text stock and include only a documented binding allowance.', 'A 160-page text block creates 80 leaves. At 0.095 mm per leaf plus 0.50 mm allowance, the planning spine is 8.10 mm.', 'Book Spine Width Calculator', 'Book Binding and Spine Reference'],
    'booklet-creep.html': ['Booklet creep', 'Creep is the outward displacement created as folded sheets nest in a saddle-stitched booklet. It becomes relevant when inner pages reach a trim line that outer pages do not.', 'A 64-page booklet contains 16 nested sheets. With 0.085 mm folded-sheet caliper, plan about 1.28 mm of outer-to-inner adjustment.', 'Booklet Creep Calculator', 'Binding Method and Page Count Reference'],
    'dpi-ppi.html': ['DPI and PPI', 'PPI describes image pixels distributed across a placed size; DPI describes dots or marks placed by an output device. The two terms meet in a print workflow but are not interchangeable.', 'A 3,000-pixel image placed at 10 inches is 300 PPI. The RIP and platesetter may operate at a much higher device DPI.', 'DPI and Print Size Calculator', 'Print Resolution and Viewing Distance Reference'],
    'gsm-basis-weight.html': ['GSM and basis weight', 'GSM is a metric mass-per-area measure. Basis weight is pounds for a stated number of sheets at a stated basis size, so paper grade and basis dimensions are essential.', 'A 70 lb 25 by 38 inch stock converts near 104 gsm; the same pound value on another basis size is not the same stock mass.', 'GSM and Basis Weight Converter', 'Paper GSM and Basis Weight Reference'],
    'n-up-layouts.html': ['N-up layout planning', 'N-up is the number of finished items that fit on a press sheet after artwork geometry and production reservations are considered. It is not automatically the best cutting or press layout.', 'A 500 by 700 mm printable area may hold 30 cards at the entered orientation; gripper, gutters and cutting lanes can reduce the certified layout.', 'N-Up Printing Calculator', 'Commercial Printing Margin and Gripper Reference'],
    'paper-job-weight.html': ['Paper job-weight estimation', 'Paper weight starts with sheet area and GSM, then becomes useful when it is multiplied by the gross parent-sheet quantity. Treat cover, inserts, boards and packaging as separate lines.', 'One 700 by 500 mm, 120 gsm sheet weighs 42 g. A 5,000-sheet press allocation is about 210 kg before packaging.', 'Paper Weight Calculator', 'Paper GSM and Basis Weight Reference'],
    'parent-sheet-size.html': ['Parent-sheet selection', 'Choose a parent sheet from the printer or merchant’s available sizes, then test usable area—not just physical dimensions—against the finished item, bleed, gripper and cutting plan.', 'A layout that looks 30-up on a 500 by 700 mm sheet can be less practical than 24-up if the first option loses too much space to gripper and trim.', 'Print Imposition Calculator', 'Paper Size Reference'],
    'press-sheets-spoilage.html': ['Press sheets and spoilage', 'Net press sheets come from required saleable quantity divided by verified items per sheet. Spoilage is a separate gross-up that must identify whether it covers press, finishing or both.', 'For 10,000 pieces at 8-up, the net is 1,250 sheets; 5% press spoilage produces a 1,313-sheet planning figure after rounding.', 'Press Sheets Required Calculator', 'Commercial Printing Margin and Gripper Reference'],
    'print-imposition.html': ['Print imposition', 'Imposition turns the finished size into a press-sheet layout with bleed, non-print margins, gripper and orientation options. It is where a geometrically valid design is tested against production space.', 'Compare normal and rotated 90 by 50 mm cards on the chosen parent sheet before pricing; the highest count still needs a cutting and press-side review.', 'Print Imposition Calculator', 'Paper Size Reference'],
    'print-job-cost.html': ['Print job cost estimation', 'A production estimate separates fixed setup from variable material, labour and finishing cost before dividing by saleable quantity. That makes a quantity change visible instead of hiding it in a single unit price.', 'With 1,000 total direct cost for 2,000 saleable pieces, direct cost is 0.50 each before overhead and margin.', 'Print Job Cost Calculator', 'Print Production Units and Conversions'],
    'print-run-time.html': ['Print run-time scheduling', 'Net runtime is impressions divided by sustainable speed, adjusted by passes when the job truly requires sequential passes. Makeready, wash-up, drying and finishing are scheduled separately.', 'Twelve thousand impressions at 6,000 per hour across four passes produces eight net press hours, before setup and downstream capacity.', 'Print Run Time Calculator', 'Print Production Units and Conversions'],
    'signatures.html': ['Book signatures', 'A signature is a folded group of pages determined by press format and fold pattern. Page count must include blank pages, and the chosen pages-per-signature must fit the actual form.', 'A 192-page book in 16-page signatures has 12 signatures; mixed sections may be needed when inserts or colour forms differ.', 'Signature Count Calculator', 'Binding Method and Page Count Reference'],
    'wide-format-material.html': ['Wide-format material usage', 'Wide-format planning converts printed face area into linear media use at the printer’s usable width. Leaders, trailers, panel gaps, seams and damaged roll edge are real consumption, not optional footnotes.', 'A 30 m² graphic on 1.5 m usable media needs 20 linear metres before panel gaps and machine lead allowance.', 'Roll Length Calculator', 'Print Resolution and Viewing Distance Reference']
  },
  reference: {
    'binding-page-count.html': ['Binding method and page count', 'Saddle stitching normally needs a total page count divisible by four because each folded sheet contributes four pages. Perfect binding and other methods can accept different constructions, subject to the supplier workflow.', 'A 34-page saddle-stitched draft needs two blank pages or a revised method; a 192-page perfect-bound book may be grouped into 16-page signatures for manufacturing convenience.', 'Signature Count Calculator', 'How Signatures Work in Book Printing'],
    'binding-spine.html': ['Book binding and spine', 'Spine width is the compressed thickness of the text block plus binding-specific construction. It differs from cover spread width, which adds the front and back panels and bleed.', 'For 160 pages on 0.095 mm stock, 80 leaves contribute 7.60 mm before a documented 0.50 mm allowance.', 'Book Spine Width Calculator', 'How to Estimate Book Spine Width'],
    'bleed-sizes.html': ['Commercial print bleed', 'Bleed is intentional image extension beyond trim so slight cutting movement does not create a white edge. It is measured per cut edge; trim remains the finished dimension.', 'A 90 by 50 mm card with 3 mm bleed on every edge becomes a 96 by 56 mm artwork file.', 'Bleed Size Calculator', 'Understanding Bleed, Trim and Safe Area'],
    'gsm-basis.html': ['GSM and basis weight', 'GSM is grams per square metre. Basis weight is pounds for a stated quantity of sheets at a named basis size, so it cannot be converted responsibly without grade and dimensions.', 'A 70 lb stock at 25 by 38 inches is about 104 gsm, while the same pounds on a different basis sheet means something else.', 'GSM and Basis Weight Converter', 'How Paper GSM and Basis Weight Work'],
    'margin-gripper.html': ['Margins and gripper', 'A gripper is the press-side area used to carry a sheet; it is not a decorative outer margin or bleed. A printable layout also needs any side-guide, colour-bar and finishing reservations stated separately.', 'If a 12 mm gripper is reserved on a 500 mm sheet direction, only the remaining printable dimension is available to the imposed work.', 'Gripper & Margin Allowance Calculator', 'How to Choose Parent Sheet Size'],
    'paper-caliper.html': ['Paper caliper', 'Caliper is the thickness of a sheet, usually measured under a stated pressure. It is not reliably inferred from GSM because fibre, coating, bulk and compression differ between stocks.', 'A 100-sheet compressed stack that measures 10 mm has a 0.10 mm planning caliper per sheet.', 'Paper Thickness Calculator', 'How to Estimate Book Spine Width'],
    'paper-sizes.html': ['Paper sizes', 'A paper size reference distinguishes finished trim, flat size, parent sheet and press sheet. The relevant size is the one being bought, imposed or trimmed at that workflow stage.', 'A 210 by 297 mm A4 finished page may be imposed multiple-up on a much larger parent sheet; calculating stock weight from A4 would understate purchase needs.', 'Print Imposition Calculator', 'How to Choose Parent Sheet Size'],
    'resolution-viewing.html': ['Resolution and viewing distance', 'Effective PPI comes from image pixels divided by final placed size. Appropriate PPI depends on how close viewers stand and on the image content; it is not the output device’s DPI.', 'A 7,200-pixel image at 120 inches is 60 PPI, which may suit distant viewing but should be reviewed for close retail inspection.', 'Wide-Format Resolution Calculator', 'DPI and PPI for Commercial Printing'],
    'units.html': ['Print production units', 'Print work combines dimensional units, area, mass, image resolution and production counts. Convert deliberately: millimetres and inches describe length, GSM describes mass per area, and impressions are not always physical sheets.', 'A 700 by 500 mm sheet is 0.35 m²; at 120 gsm it weighs 42 g. Keeping area and mass separate prevents a common estimating error.', 'Paper Weight Calculator', 'How to Estimate Paper Weight for a Print Job']
  }
};

function articleContent(type, file, html) {
  const [topic, context, example, tool, related] = articles[type][file];
  const title = titleOf(html);
  const toolSlug = Object.entries(calculators).find(([, value]) => tool.toLowerCase().includes(value[0].replace(/planning|and|for|a|the/gi, '').trim().toLowerCase().split(' ')[0]))?.[0] || 'print-imposition-calculator.html';
  const toolHref = `/tools/${toolSlug}`;
  return `<p class="crumb"><a href="/">Home</a> / <a href="/${type}/">${type}</a></p><p class="eyebrow">Production notes</p><h1>${esc(title)}</h1><p class="lead">A practical reference for making a documented production decision, not a substitute for the approved job specification.</p>
${tag('Purpose and production context', `<p>${esc(title)} addresses this production question: ${esc(context)}</p><p>Use this ${esc(type === 'guides' ? 'guide' : 'reference')} on ${esc(topic)} when preparing a quote, artwork brief, preflight record or production ticket. State the source of each measurement so a later operator can repeat the decision.</p>`)}
${tag('Definitions and distinctions', `<p>This ${esc(type === 'guides' ? 'guide' : 'reference')} separates ${esc(topic)} from similar measurements that occur earlier or later in the workflow. Identify whether the value refers to finished trim, flat artwork, parent stock, printable area, a physical sheet, an impression, or a saleable piece.</p><p>Write the ${esc(type === 'guides' ? 'guide' : 'reference')} ${esc(topic)} unit beside every number. A correct formula applied to mismatched units or bases is still a production error.</p>`)}
${tag('Inputs, units and method', `<p>Begin this ${esc(type === 'guides' ? 'guide' : 'reference')} ${esc(topic)} check with the approved job ticket, stock data sheet, press specification, RIP setting or a documented physical measurement. Convert units before calculation and preserve the original source value in the job record.</p><p>Round ${esc(type === 'guides' ? 'guide' : 'reference')} ${esc(topic)} planning quantities only at the point where stock, sheets, signatures or whole jobs must be purchased or scheduled.</p>`)}
${tag('Worked production example', `<p>In this ${esc(title)} example, ${esc(example)}</p><p>The practical ${esc(type === 'guides' ? 'guide' : 'reference')} ${esc(topic)} value is not the number by itself: it tells the estimator what to reserve, the designer what file geometry to use, or the operator what to verify before release.</p>`)}
${tag('Decision checklist', `<ol><li>Confirm the ${esc(topic)} production stage and relevant physical basis.</li><li>Record the ${esc(topic)} source unit and convert only once.</li><li>Use the related calculator to test documented ${esc(topic)} inputs.</li><li>Check the result against the press, supplier or finishing condition that applies.</li><li>Carry the ${esc(topic)} assumption into the quote or production ticket.</li></ol>`)}
${tag(type === 'guides' ? 'Production handoff and preflight' : 'Using this reference at the press desk', type === 'guides' ? `<p>For ${esc(title)}, put the approved ${esc(topic)} value, its unit, source and any conversion on the job ticket. A designer should see the required file or trim basis; an estimator should see the purchasing or quantity basis; the production operator should see the machine-side condition that still needs confirmation.</p><p>Before release, compare the ${esc(topic)} result with the supplied artwork, stock description and finishing sequence. If one of those items changes, repeat the relevant calculation instead of carrying an old value forward. This is especially important when a job moves from an estimate based on a parent sheet to a layout based on printable area.</p><p>Use a marked proof, folding dummy or measured stock sample when the ${esc(topic)} decision is close to a tolerance. That physical check does not replace the calculation; it tests whether the job conditions match the assumptions recorded in it.</p><p>For this ${esc(title)} guide, finish the review by naming the owner of the next decision and its deadline. A calculation that is not transferred to the quote, preflight or production ticket is easy to lose when the job changes hands.</p>` : `<p>Keep this ${esc(topic)} reference beside the job ticket rather than relying on memory. Record whether the value came from a supplied specification, a measured sample or a planning assumption, because those sources have different authority in a production review.</p><p>When ${esc(title)} affects material ordering, imposition or finishing, preserve enough context for another operator to reproduce it: finished size, parent or press sheet where relevant, unit conversion, approved allowance and the point at which a value was rounded.</p>`)}
${tag('Common mistakes and cautions', `<p>Do not treat this ${esc(type === 'guides' ? 'guide' : 'reference')} ${esc(topic)} planning value as a universal machine setting. Avoid mixing gross and saleable quantities, physical sheet size and printable area, or image PPI and output-device DPI.</p><p>Actual stock, press, RIP, drying, coating, binding and finishing conditions can change the ${esc(type === 'guides' ? 'guide' : 'reference')} ${esc(topic)} allowance. Confirm the condition that matters for this job.</p>`)}
${tag('Related workflow', `<p>Use <a href="${toolHref}">${esc(tool)}</a> when ${esc(title)} reaches its calculation step, then consult <a href="/${type === 'guides' ? 'reference' : 'guides'}/">${esc(related)}</a> before releasing the production instruction.</p><p>Last reviewed: 2026-07-27</p>`)}
`;
}

for (const file of Object.keys(calculators)) {
  const path = `tools/${file}`; const html = fs.readFileSync(path, 'utf8');
  const replacement = calcContent(file, html);
  const cleaned = html.replace(/<p>Enter job-specific values in one unit system, then compare the result with your press, material, or finishing specification\.<\/p>/g, '').replace(/<p>The displayed result uses the dimensional or quantity relationship represented by the three inputs; every input remains editable\.<\/p>/g, '');
  const updated = cleaned.replace(/<section class="content-detail">[\s\S]*?<\/main>/, `${replacement}</main>`);
  if (!updated.includes('<section class="content-detail">')) throw new Error(`Calculator replacement failed: ${path}`);
  fs.writeFileSync(path, updated);
}
for (const type of ['guides', 'reference']) for (const file of Object.keys(articles[type])) {
  const path = `${type}/${file}`; const html = fs.readFileSync(path, 'utf8');
  const updated = html.replace(/<main>[\s\S]*?<\/main>/, `<main>${articleContent(type, file, html)}</main>`);
  if (updated === html) throw new Error(`Article replacement failed: ${path}`);
  fs.writeFileSync(path, updated);
}

console.log(`Rebuilt ${Object.keys(calculators).length} calculators, ${Object.keys(articles.guides).length} guides and ${Object.keys(articles.reference).length} reference pages.`);
